language: objective-c
osx_image: xcode7.3

script:
    - xcodebuild -workspace src/Dono.xcworkspace -scheme Dono | xcpretty

notifications:
  email:
      recipients:
        - panos.sakkos@gmail.com
      on_failure: always
      on_success: never
